### ISSUE TITLE
allowing timeout parameters to be passed in

### ISSUE THREAD

**Issue by chunkiat82** [skoranga/node-connection-tester#1]
Hi,

Do you think we should allow the timeout parameters to be a variable to?

Thanks

for the above suggested requirement, i recommend this change https://github.com/chunkiat82/node-connection-tester/commit/6201ad15d9fa70b68774ac0c6a7df193ff783b57

this change is backward compatible for migration

**Comment by skoranga** [comment]
@chunkiat82 changes looks good. can you submit this as PR?

**Comment by skoranga** [comment]
https://github.com/skoranga/node-connection-tester/pull/2.

published `connection-tester@0.1.0`

**Comment by chunkiat82** [comment]
Thanks
